User.create!(username:  "Admin",
             email:     "admin@admin.pt",
             password:              "123456",
             password_confirmation: "123456",
             admin: true,
             activated: true,
             activated_at: Time.zone.now)



  username = "Manel"
  email    = "manel@mail.pt"
  password = "123456"
  User.create!(username:  username,
               email:     email,
               password:              password,
               password_confirmation: password,
               activated: true,
               activated_at: Time.zone.now)


#----------------------------------------------------------------------------------#
#                                                                                  #
#                                                                                  #
#                                  Players                                         #
#                                                                                  #
#                                                                                  #
#----------------------------------------------------------------------------------#
Player.create(name:"Maicon", position:"DEF", value:57, real_team:"Porto")
Player.create(name:"Silvestre Varela", position:"FOR", value:54, real_team:"Porto")
Player.create(name:"Maxi Pereira", position:"DEF", value:54, real_team:"Porto")
Player.create(name:"Helton", position:"GK", value:54, real_team:"Porto")
Player.create(name:"Bruno Martins Indi", position:"DEF", value:56, real_team:"Porto")
Player.create(name:"Iván Marcano", position:"DEF", value:55, real_team:"Porto")
Player.create(name:"José Ángel", position:"DEF", value:55, real_team:"Porto")
Player.create(name:"Rúben Neves", position:"MID", value:53, real_team:"Porto")
Player.create(name:"Héctor Herrera", position:"MID", value:60, real_team:"Porto")
Player.create(name:"Evandro", position:"MID", value:56, real_team:"Porto")
Player.create(name:"Yacine Brahimi", position:"FOR", value:66, real_team:"Porto")
Player.create(name:"Kelvin", position:"FOR", value:55, real_team:"Porto")
Player.create(name:"Vincent Aboubakar", position:"FOR", value:56, real_team:"Porto")
Player.create(name:"Miguel Layún", position:"DEF", value:55, real_team:"Porto")
Player.create(name:"Iker Casillas", position:"GK", value:54, real_team:"Porto")
Player.create(name:"Alberto Bueno", position:"MID", value:56, real_team:"Porto")
Player.create(name:"José Sá", position:"GK", value:57, real_team:"Porto")
Player.create(name:"Danilo Pereira", position:"MID", value:55, real_team:"Porto")
Player.create(name:"Moussa Marega", position:"FOR", value:55, real_team:"Porto")
Player.create(name:"André André", position:"MID", value:55, real_team:"Porto")
Player.create(name:"Sérgio Oliveira", position:"MID", value:57, real_team:"Porto")
Player.create(name:"Hyun-Jun Suk", position:"FOR", value:55, real_team:"Porto")
Player.create(name:"Jesús Corona", position:"FOR", value:57, real_team:"Porto")
Player.create(name:"André Silva", position:"FOR", value:53, real_team:"Porto")
Player.create(name:"Walter", position:"FOR", value:56, real_team:"Porto")
Player.create(name:"Manuel Neuer", position:"GK", value:76, real_team:"Bayern")
Player.create(name:"Sven Ulreich", position:"GK", value:56, real_team:"Bayern")
Player.create(name:"Tom Starke", position:"GK", value:52, real_team:"Bayern")
Player.create(name:"Ivan Lucic", position:"GK", value:53, real_team:"Bayern")
Player.create(name:"Jérôme Boateng", position:"DEF", value:71, real_team:"Bayern")
Player.create(name:"Medhi Benatia", position:"DEF", value:67, real_team:"Bayern")
Player.create(name:"Holger Badstuber", position:"DEF", value:56, real_team:"Bayern")
Player.create(name:"David Alaba", position:"DEF", value:77, real_team:"Bayern")
Player.create(name:"Juan Bernat", position:"DEF", value:61, real_team:"Bayern")
Player.create(name:"Philipp Lahm", position:"DEF", value:62, real_team:"Bayern")
Player.create(name:"Javi Martínez", position:"DEF", value:66, real_team:"Bayern")
Player.create(name:"Sebastian Rode", position:"MID", value:56, real_team:"Bayern")
Player.create(name:"Xabi Alonso", position:"MID", value:52, real_team:"Bayern")
Player.create(name:"Joshua Kimmich", position:"MID", value:55, real_team:"Bayern")
Player.create(name:"Arturo Vidal", position:"MID", value:75, real_team:"Bayern")
Player.create(name:"Thiago", position:"MID", value:67, real_team:"Bayern")
Player.create(name:"Mario Götze", position:"MID", value:76, real_team:"Bayern")
Player.create(name:"Franck Ribéry", position:"FOR", value:52, real_team:"Bayern")
Player.create(name:"Kingsley Coman", position:"FOR", value:53, real_team:"Bayern")
Player.create(name:"Julian Green", position:"FOR", value:53, real_team:"Bayern")
Player.create(name:"Arjen Robben", position:"FOR", value:62, real_team:"Bayern")
Player.create(name:"Douglas Costa", position:"FOR", value:71, real_team:"Bayern")
Player.create(name:"Thomas Müller", position:"FOR", value:91, real_team:"Bayern")
Player.create(name:"Robert Lewandowski", position:"FOR", value:85, real_team:"Bayern")
Player.create(name:"Serdar Tasci", position:"DEF", value:57, real_team:"Bayern")
Player.create(name:"Roman Bürki", position:"GK", value:57, real_team:"Dortmund")
Player.create(name:"Roman Weidenfeller", position:"GK", value:52, real_team:"Dortmund")
Player.create(name:"Hendrik Bonmann", position:"GK", value:55, real_team:"Dortmund")
Player.create(name:"Mats Hummels", position:"DEF", value:70, real_team:"Dortmund")
Player.create(name:"Sokratis", position:"DEF", value:66, real_team:"Dortmund")
Player.create(name:"Neven Subotic", position:"DEF", value:56, real_team:"Dortmund")
Player.create(name:"Matthias Ginter", position:"DEF", value:55, real_team:"Dortmund")
Player.create(name:"Marcel Schmelzer", position:"DEF", value:55, real_team:"Dortmund")
Player.create(name:"Joo-Ho Park", position:"DEF", value:57, real_team:"Dortmund")
Player.create(name:"Lukasz Piszczek", position:"DEF", value:55, real_team:"Dortmund")
Player.create(name:"Erik Durm", position:"DEF", value:56, real_team:"Dortmund")
Player.create(name:"Sven Bender", position:"DEF", value:56, real_team:"Dortmund")
Player.create(name:"Julian Weigl", position:"MID", value:55, real_team:"Dortmund")
Player.create(name:"Ilkay Gündogan", position:"MID", value:66, real_team:"Dortmund")
Player.create(name:"Gonzalo Castro", position:"MID", value:56, real_team:"Dortmund")
Player.create(name:"Nuri Sahin", position:"MID", value:55, real_team:"Dortmund")
Player.create(name:"Moritz Leitner", position:"MID", value:57, real_team:"Dortmund")
Player.create(name:"Henrikh Mkhitaryan", position:"FOR", value:66, real_team:"Dortmund")
Player.create(name:"Shinji Kagawa", position:"MID", value:56, real_team:"Dortmund")
Player.create(name:"Marco Reus", position:"FOR", value:76, real_team:"Dortmund")
Player.create(name:"Pierre-Emerick Aubameyang", position:"FOR", value:77, real_team:"Dortmund")
Player.create(name:"Adrián Ramos", position:"FOR", value:57, real_team:"Dortmund")
Player.create(name:"Christian Pulisic", position:"MID", value:55, real_team:"Dortmund")
Player.create(name:"Felix Passlack", position:"FOR", value:55, real_team:"Dortmund")
Player.create(name:"Ángel di María", position:"FOR", value:76, real_team:"PSG")
Player.create(name:"Kevin Trapp", position:"GK", value:55, real_team:"PSG")
Player.create(name:"Benjamin Stambouli", position:"MID", value:56, real_team:"PSG")
Player.create(name:"Layvin Kurzawa", position:"DEF", value:60, real_team:"PSG")
Player.create(name:"Salvatore Sirigu", position:"GK", value:57, real_team:"PSG")
Player.create(name:"Nicolas Douchez", position:"GK", value:54, real_team:"PSG")
Player.create(name:"Thiago Silva", position:"DEF", value:63, real_team:"PSG")
Player.create(name:"David Luiz", position:"DEF", value:67, real_team:"PSG")
Player.create(name:"Marquinhos", position:"DEF", value:64, real_team:"PSG")
Player.create(name:"Maxwell", position:"DEF", value:54, real_team:"PSG")
Player.create(name:"Serge Aurier", position:"DEF", value:55, real_team:"PSG")
Player.create(name:"Gregory van der Wiel", position:"DEF", value:57, real_team:"PSG")
Player.create(name:"Thiago Motta", position:"MID", value:54, real_team:"PSG")
Player.create(name:"Marco Verratti", position:"MID", value:71, real_team:"PSG")
Player.create(name:"Blaise Matuidi", position:"MID", value:65, real_team:"PSG")
Player.create(name:"Adrien Rabiot", position:"MID", value:54, real_team:"PSG")
Player.create(name:"Javier Pastore", position:"MID", value:65, real_team:"PSG")
Player.create(name:"Ezequiel Lavezzi", position:"FOR", value:53, real_team:"PSG")
Player.create(name:"Edinson Cavani", position:"FOR", value:75, real_team:"PSG")
Player.create(name:"Zlatan Ibrahimovic", position:"FOR", value:52, real_team:"PSG")
Player.create(name:"Hervin Ongenda", position:"FOR", value:54, real_team:"PSG")
Player.create(name:"Presnel Kimpembe", position:"DEF", value:55, real_team:"PSG")
Player.create(name:"Jean-Kévin Augustin", position:"FOR", value:53, real_team:"PSG")
Player.create(name:"Ederson", position:"GK", value:54, real_team:"Lisbon")
Player.create(name:"Konstantinos Mitroglou", position:"FOR", value:55, real_team:"Lisbon")
Player.create(name:"Júlio César", position:"GK", value:54, real_team:"Lisbon")
Player.create(name:"Paulo Lopes", position:"GK", value:54, real_team:"Lisbon")
Player.create(name:"Lisandro López", position:"DEF", value:57, real_team:"Lisbon")
Player.create(name:"Luisão", position:"DEF", value:52, real_team:"Lisbon")
Player.create(name:"Jardel", position:"DEF", value:56, real_team:"Lisbon")
Player.create(name:"Eliseu", position:"DEF", value:52, real_team:"Lisbon")
Player.create(name:"André Almeida", position:"DEF", value:57, real_team:"Lisbon")
Player.create(name:"Sílvio", position:"DEF", value:56, real_team:"Lisbon")
Player.create(name:"Andreas Samaris", position:"MID", value:56, real_team:"Lisbon")
Player.create(name:"Ljubomir Fejsa", position:"MID", value:55, real_team:"Lisbon")
Player.create(name:"Pizzi", position:"FOR", value:55, real_team:"Lisbon")
Player.create(name:"Jonas", position:"FOR", value:52, real_team:"Lisbon")
Player.create(name:"Talisca", position:"MID", value:55, real_team:"Lisbon")
Player.create(name:"Raúl Jiménez", position:"FOR", value:56, real_team:"Lisbon")
Player.create(name:"Raphael Guzzo", position:"MID", value:54, real_team:"Lisbon")
Player.create(name:"Victor Lindelöf", position:"DEF", value:53, real_team:"Lisbon")
Player.create(name:"Nélson Semedo", position:"DEF", value:53, real_team:"Lisbon")
Player.create(name:"Toto Salvio", position:"FOR", value:66, real_team:"Lisbon")
Player.create(name:"Mehdi Carcela-González", position:"FOR", value:57, real_team:"Lisbon")
Player.create(name:"Gonçalo Guedes", position:"FOR", value:54, real_team:"Lisbon")
Player.create(name:"Álex Grimaldo", position:"DEF", value:55, real_team:"Lisbon")
Player.create(name:"Renato Sanches", position:"MID", value:53, real_team:"Lisbon")
Player.create(name:"Nico Gaitán", position:"FOR", value:67, real_team:"Lisbon")
Player.create(name:"Luka Jovic", position:"FOR", value:53, real_team:"Lisbon")
Player.create(name:"Kevin de Bruyne", position:"FOR", value:80, real_team:"ManCity")
Player.create(name:"Wilfried Bony", position:"FOR", value:67, real_team:"ManCity")
Player.create(name:"Fabian Delph", position:"MID", value:56, real_team:"ManCity")
Player.create(name:"Raheem Sterling", position:"FOR", value:74, real_team:"ManCity")
Player.create(name:"Joe Hart", position:"GK", value:62, real_team:"ManCity")
Player.create(name:"Willy Caballero", position:"GK", value:54, real_team:"ManCity")
Player.create(name:"Richard Wright", position:"GK", value:54, real_team:"ManCity")
Player.create(name:"Eliaquim Mangala", position:"DEF", value:66, real_team:"ManCity")
Player.create(name:"Vincent Kompany", position:"DEF", value:66, real_team:"ManCity")
Player.create(name:"Martín Demichelis", position:"DEF", value:52, real_team:"ManCity")
Player.create(name:"Aleksandar Kolarov", position:"DEF", value:57, real_team:"ManCity")
Player.create(name:"Gaël Clichy", position:"DEF", value:56, real_team:"ManCity")
Player.create(name:"Pablo Zabaleta", position:"DEF", value:57, real_team:"ManCity")
Player.create(name:"Bacary Sagna", position:"DEF", value:53, real_team:"ManCity")
Player.create(name:"Fernandinho", position:"MID", value:64, real_team:"ManCity")
Player.create(name:"Yaya Touré", position:"MID", value:62, real_team:"ManCity")
Player.create(name:"Samir Nasri", position:"FOR", value:67, real_team:"ManCity")
Player.create(name:"David Silva", position:"MID", value:70, real_team:"ManCity")
Player.create(name:"Jesús Navas", position:"FOR", value:61, real_team:"ManCity")
Player.create(name:"Nicolás Otamendi", position:"DEF", value:72, real_team:"ManCity")
Player.create(name:"Sergio Agüero", position:"FOR", value:82, real_team:"ManCity")
Player.create(name:"Kelechi Iheanacho", position:"FOR", value:53, real_team:"ManCity")
Player.create(name:"Luke Brattan", position:"MID", value:56, real_team:"ManCity")
Player.create(name:"Gianluigi Buffon", position:"GK", value:52, real_team:"Juventus")
Player.create(name:"Rubinho", position:"GK", value:52, real_team:"Juventus")
Player.create(name:"Leonardo Bonucci", position:"DEF", value:66, real_team:"Juventus")
Player.create(name:"Giorgio Chiellini", position:"DEF", value:54, real_team:"Juventus")
Player.create(name:"Martín Cáceres", position:"DEF", value:57, real_team:"Juventus")
Player.create(name:"Andrea Barzagli", position:"DEF", value:53, real_team:"Juventus")
Player.create(name:"Patrice Evra", position:"DEF", value:54, real_team:"Juventus")
Player.create(name:"Stephan Lichtsteiner", position:"DEF", value:54, real_team:"Juventus")
Player.create(name:"Paul Pogba", position:"MID", value:81, real_team:"Juventus")
Player.create(name:"Claudio Marchisio", position:"MID", value:66, real_team:"Juventus")
Player.create(name:"Roberto Pereyra", position:"MID", value:62, real_team:"Juventus")
Player.create(name:"Simone Padoin", position:"MID", value:53, real_team:"Juventus")
Player.create(name:"Kwadwo Asamoah", position:"MID", value:56, real_team:"Juventus")
Player.create(name:"Álvaro Morata", position:"FOR", value:66, real_team:"Juventus")
Player.create(name:"Neto", position:"GK", value:57, real_team:"Juventus")
Player.create(name:"Juan Cuadrado", position:"MID", value:66, real_team:"Juventus")
Player.create(name:"Simone Zaza", position:"FOR", value:56, real_team:"Juventus")
Player.create(name:"Paulo Dybala", position:"FOR", value:70, real_team:"Juventus")
Player.create(name:"Daniele Rugani", position:"DEF", value:55, real_team:"Juventus")
Player.create(name:"Stefano Sturaro", position:"MID", value:55, real_team:"Juventus")
Player.create(name:"Hernanes", position:"MID", value:56, real_team:"Juventus")
Player.create(name:"Alex Sandro", position:"DEF", value:66, real_team:"Juventus")
Player.create(name:"Mario Lemina", position:"MID", value:53, real_team:"Juventus")
Player.create(name:"Sami Khedira", position:"MID", value:62, real_team:"Juventus")
Player.create(name:"Mario Mandzukic", position:"FOR", value:62, real_team:"Juventus")
Player.create(name:"Emil Audero", position:"GK", value:54, real_team:"Juventus")
Player.create(name:"Yuri Lodygin", position:"GK", value:55, real_team:"Zenit")
Player.create(name:"Vyacheslav Malafeev", position:"GK", value:54, real_team:"Zenit")
Player.create(name:"Ezequiel Garay", position:"DEF", value:67, real_team:"Zenit")
Player.create(name:"Nicolas Lombaerts", position:"DEF", value:53, real_team:"Zenit")
Player.create(name:"Domenico Criscito", position:"DEF", value:57, real_team:"Zenit")
Player.create(name:"Igor Smolnikov", position:"DEF", value:55, real_team:"Zenit")
Player.create(name:"Aleksandr Anyukov", position:"DEF", value:54, real_team:"Zenit")
Player.create(name:"Javi García", position:"MID", value:62, real_team:"Zenit")
Player.create(name:"Axel Witsel", position:"MID", value:67, real_team:"Zenit")
Player.create(name:"Viktor Faizulin", position:"MID", value:57, real_team:"Zenit")
Player.create(name:"Oleg Shatov", position:"MID", value:56, real_team:"Zenit")
Player.create(name:"Aleksandr Ryazantsev", position:"MID", value:56, real_team:"Zenit")
Player.create(name:"Ivan Solovjev", position:"MID", value:57, real_team:"Zenit")
Player.create(name:"Danny", position:"MID", value:52, real_team:"Zenit")
Player.create(name:"Hulk", position:"FOR", value:71, real_team:"Zenit")
Player.create(name:"Aleksandr Kerzhakov", position:"FOR", value:54, real_team:"Zenit")
Player.create(name:"Mikhail Kerzhakov", position:"GK", value:57, real_team:"Zenit")
Player.create(name:"Artur Yusupov", position:"MID", value:55, real_team:"Zenit")
Player.create(name:"Artem Dzyuba", position:"FOR", value:57, real_team:"Zenit")
Player.create(name:"Marco van Ginkel", position:"MID", value:57, real_team:"Eindhoven")
Player.create(name:"Maxime Lestienne", position:"FOR", value:57, real_team:"Eindhoven")
Player.create(name:"Héctor Moreno", position:"DEF", value:55, real_team:"Eindhoven")
Player.create(name:"Jeroen Zoet", position:"GK", value:55, real_team:"Eindhoven")
Player.create(name:"Remko Pasveer", position:"GK", value:53, real_team:"Eindhoven")
Player.create(name:"Luuk Koopmans", position:"GK", value:55, real_team:"Eindhoven")
Player.create(name:"Jeffrey Bruma", position:"DEF", value:56, real_team:"Eindhoven")
Player.create(name:"Nicolas Isimat-Mirin", position:"DEF", value:57, real_team:"Eindhoven")
Player.create(name:"Menno Koch", position:"DEF", value:54, real_team:"Eindhoven")
Player.create(name:"Jordy de Wijs", position:"DEF", value:53, real_team:"Eindhoven")
Player.create(name:"Suently Alberto", position:"DEF", value:53, real_team:"Eindhoven")
Player.create(name:"Jetro Willems", position:"DEF", value:55, real_team:"Eindhoven")
Player.create(name:"Simon Poulsen", position:"DEF", value:53, real_team:"Eindhoven")
Player.create(name:"Santiago Arias", position:"DEF", value:56, real_team:"Eindhoven")
Player.create(name:"Joshua Brenet", position:"DEF", value:55, real_team:"Eindhoven")
Player.create(name:"Andrés Guardado", position:"MID", value:55, real_team:"Eindhoven")
Player.create(name:"Stijn Schaars", position:"MID", value:52, real_team:"Eindhoven")
Player.create(name:"Jorrit Hendrix", position:"MID", value:55, real_team:"Eindhoven")
Player.create(name:"Davy Pröpper", position:"MID", value:56, real_team:"Eindhoven")
Player.create(name:"Adam Maher", position:"MID", value:54, real_team:"Eindhoven")
Player.create(name:"Gastón Pereiro", position:"FOR", value:54, real_team:"Eindhoven")
Player.create(name:"Kenneth Paal", position:"MID", value:55, real_team:"Eindhoven")
Player.create(name:"Steven Bergwijn", position:"FOR", value:55, real_team:"Eindhoven")
Player.create(name:"Luciano Narsingh", position:"FOR", value:56, real_team:"Eindhoven")
Player.create(name:"Florian Jozefzoon", position:"FOR", value:55, real_team:"Eindhoven")
Player.create(name:"Luuk de Jong", position:"FOR", value:56, real_team:"Eindhoven")
Player.create(name:"Jürgen Locadia", position:"FOR", value:54, real_team:"Eindhoven")
Player.create(name:"Facundo Ferreyra", position:"FOR", value:57, real_team:"Shakhtar")
Player.create(name:"Andriy Pyatov", position:"GK", value:53, real_team:"Shakhtar")
Player.create(name:"Anton Kanibolotsky", position:"GK", value:57, real_team:"Shakhtar")
Player.create(name:"Yaroslav Rakitsky", position:"DEF", value:55, real_team:"Shakhtar")
Player.create(name:"Oleksandr Kucher", position:"DEF", value:54, real_team:"Shakhtar")
Player.create(name:"Ivan Ordets", position:"DEF", value:57, real_team:"Shakhtar")
Player.create(name:"Sergiy Kryvtsov", position:"DEF", value:55, real_team:"Shakhtar")
Player.create(name:"Márcio Azevedo", position:"DEF", value:55, real_team:"Shakhtar")
Player.create(name:"Ismaily", position:"DEF", value:57, real_team:"Shakhtar")
Player.create(name:"Vyacheslav Shevchuk", position:"DEF", value:53, real_team:"Shakhtar")
Player.create(name:"Darijo Srna", position:"DEF", value:52, real_team:"Shakhtar")
Player.create(name:"Taras Stepanenko", position:"MID", value:55, real_team:"Shakhtar")
Player.create(name:"Fred", position:"MID", value:55, real_team:"Shakhtar")
Player.create(name:"Vitali Vitsenets", position:"MID", value:56, real_team:"Shakhtar")
Player.create(name:"Alex Teixeira", position:"MID", value:66, real_team:"Shakhtar")
Player.create(name:"Bernard", position:"FOR", value:62, real_team:"Shakhtar")
Player.create(name:"Wellington Nem", position:"FOR", value:57, real_team:"Shakhtar")
Player.create(name:"Dentinho", position:"FOR", value:56, real_team:"Shakhtar")
Player.create(name:"Marlos", position:"FOR", value:55, real_team:"Shakhtar")
Player.create(name:"Taison", position:"FOR", value:56, real_team:"Shakhtar")
Player.create(name:"Oleksandr Gladky", position:"FOR", value:56, real_team:"Shakhtar")
Player.create(name:"Bogdan Sarnavski", position:"GK", value:53, real_team:"Shakhtar")
Player.create(name:"Vasyl Kobin", position:"DEF", value:57, real_team:"Shakhtar")
Player.create(name:"Maksym Malyshev", position:"MID", value:57, real_team:"Shakhtar")
Player.create(name:"Viktor Kovalenko", position:"MID", value:53, real_team:"Shakhtar")
Player.create(name:"Sergiy Gryn", position:"FOR", value:55, real_team:"Shakhtar")
Player.create(name:"Mateo Kovacic", position:"MID", value:59, real_team:"Real Madrid")
Player.create(name:"Casemiro", position:"MID", value:57, real_team:"Real Madrid")
Player.create(name:"Kiko Casilla", position:"GK", value:56, real_team:"Real Madrid")
Player.create(name:"Lucas Vázquez", position:"FOR", value:55, real_team:"Real Madrid")
Player.create(name:"Keylor Navas", position:"GK", value:55, real_team:"Real Madrid")
Player.create(name:"Sergio Ramos", position:"DEF", value:70, real_team:"Real Madrid")
Player.create(name:"Raphaël Varane", position:"DEF", value:67, real_team:"Real Madrid")
Player.create(name:"Pepe", position:"DEF", value:54, real_team:"Real Madrid")
Player.create(name:"Nacho Fernández", position:"DEF", value:55, real_team:"Real Madrid")
Player.create(name:"Daniel Carvajal", position:"DEF", value:65, real_team:"Real Madrid")
Player.create(name:"Álvaro Arbeloa", position:"DEF", value:53, real_team:"Real Madrid")
Player.create(name:"Luka Modric", position:"MID", value:76, real_team:"Real Madrid")
Player.create(name:"Toni Kroos", position:"MID", value:75, real_team:"Real Madrid")
Player.create(name:"James Rodríguez", position:"MID", value:91, real_team:"Real Madrid")
Player.create(name:"Isco", position:"MID", value:77, real_team:"Real Madrid")
Player.create(name:"Cristiano Ronaldo", position:"FOR", value:99, real_team:"Real Madrid")
Player.create(name:"Jesé", position:"FOR", value:56, real_team:"Real Madrid")
Player.create(name:"Gareth Bale", position:"FOR", value:92, real_team:"Real Madrid")
Player.create(name:"Karim Benzema", position:"FOR", value:75, real_team:"Real Madrid")
Player.create(name:"Rubén Yáñez", position:"GK", value:53, real_team:"Real Madrid")
Player.create(name:"Marc-André ter Stegen", position:"GK", value:57, real_team:"Barcelona")
Player.create(name:"Claudio Bravo", position:"GK", value:53, real_team:"Barcelona")
Player.create(name:"Jordi Masip", position:"GK", value:55, real_team:"Barcelona")
Player.create(name:"Gerard Piqué", position:"DEF", value:71, real_team:"Barcelona")
Player.create(name:"Javier Mascherano", position:"DEF", value:54, real_team:"Barcelona")
Player.create(name:"Thomas Vermaelen", position:"DEF", value:56, real_team:"Barcelona")
Player.create(name:"Jérémy Mathieu", position:"DEF", value:53, real_team:"Barcelona")
Player.create(name:"Marc Bartra", position:"DEF", value:56, real_team:"Barcelona")
Player.create(name:"Jordi Alba", position:"DEF", value:72, real_team:"Barcelona")
Player.create(name:"Adriano", position:"DEF", value:52, real_team:"Barcelona")
Player.create(name:"Dani Alves", position:"DEF", value:52, real_team:"Barcelona")
Player.create(name:"Douglas", position:"DEF", value:55, real_team:"Barcelona")
Player.create(name:"Sergio Busquets", position:"MID", value:75, real_team:"Barcelona")
Player.create(name:"Andrés Iniesta", position:"MID", value:69, real_team:"Barcelona")
Player.create(name:"Ivan Rakitic", position:"MID", value:71, real_team:"Barcelona")
Player.create(name:"Sergi Roberto", position:"MID", value:56, real_team:"Barcelona")
Player.create(name:"Neymar", position:"FOR", value:98, real_team:"Barcelona")
Player.create(name:"Lionel Messi", position:"FOR", value:99, real_team:"Barcelona")
Player.create(name:"Luis Suárez", position:"FOR", value:97, real_team:"Barcelona")
Player.create(name:"Munir El Haddadi", position:"FOR", value:54, real_team:"Barcelona")
Player.create(name:"Sandro Ramírez", position:"FOR", value:53, real_team:"Barcelona")
Player.create(name:"Aleix Vidal", position:"DEF", value:56, real_team:"Barcelona")
Player.create(name:"Arda Turan", position:"MID", value:72, real_team:"Barcelona")
Player.create(name:"Rafinha", position:"MID", value:55, real_team:"Barcelona")
Player.create(name:"Stefan Savic", position:"DEF", value:57, real_team:"Atlético")
Player.create(name:"Filipe Luís", position:"DEF", value:57, real_team:"Atlético")
Player.create(name:"Yannick Ferreira Carrasco", position:"FOR", value:53, real_team:"Atlético")
Player.create(name:"Óliver Torres", position:"MID", value:53, real_team:"Atlético")
Player.create(name:"Luciano Vietto", position:"FOR", value:60, real_team:"Atlético")
Player.create(name:"Augusto Fernández", position:"MID", value:56, real_team:"Atlético")
Player.create(name:"Jan Oblak", position:"GK", value:62, real_team:"Atlético")
Player.create(name:"Miguel Ángel Moyà", position:"GK", value:53, real_team:"Atlético")
Player.create(name:"Diego Godín", position:"DEF", value:67, real_team:"Atlético")
Player.create(name:"José Giménez", position:"DEF", value:58, real_team:"Atlético")
Player.create(name:"Jesús Gámez", position:"DEF", value:53, real_team:"Atlético")
Player.create(name:"Gabi", position:"MID", value:52, real_team:"Atlético")
Player.create(name:"Tiago", position:"MID", value:52, real_team:"Atlético")
Player.create(name:"Koke", position:"FOR", value:75, real_team:"Atlético")
Player.create(name:"Antoine Griezmann", position:"FOR", value:75, real_team:"Atlético")
Player.create(name:"Ángel Correa", position:"FOR", value:54, real_team:"Atlético")
Player.create(name:"Fernando Torres", position:"FOR", value:53, real_team:"Atlético")
Player.create(name:"Lucas Hernández", position:"DEF", value:54, real_team:"Atlético")
Player.create(name:"Matías Kranevitter", position:"MID", value:54, real_team:"Atlético")
Player.create(name:"Saúl Níguez", position:"MID", value:55, real_team:"Atlético")
Player.create(name:"David Ospina", position:"GK", value:56, real_team:"Arsenal")
Player.create(name:"Per Mertesacker", position:"DEF", value:54, real_team:"Arsenal")
Player.create(name:"Laurent Koscielny", position:"DEF", value:62, real_team:"Arsenal")
Player.create(name:"Kieran Gibbs", position:"DEF", value:57, real_team:"Arsenal")
Player.create(name:"Nacho Monreal", position:"DEF", value:56, real_team:"Arsenal")
Player.create(name:"Calum Chambers", position:"DEF", value:54, real_team:"Arsenal")
Player.create(name:"Héctor Bellerín", position:"DEF", value:55, real_team:"Arsenal")
Player.create(name:"Mathieu Flamini", position:"MID", value:53, real_team:"Arsenal")
Player.create(name:"Mikel Arteta", position:"MID", value:52, real_team:"Arsenal")
Player.create(name:"Francis Coquelin", position:"MID", value:57, real_team:"Arsenal")
Player.create(name:"Jack Wilshere", position:"MID", value:67, real_team:"Arsenal")
Player.create(name:"Aaron Ramsey", position:"MID", value:66, real_team:"Arsenal")
Player.create(name:"Mesut Özil", position:"MID", value:71, real_team:"Arsenal")
Player.create(name:"Tomás Rosicky", position:"MID", value:54, real_team:"Arsenal")
Player.create(name:"Santi Cazorla", position:"MID", value:63, real_team:"Arsenal")
Player.create(name:"Alex Oxlade-Chamberlain", position:"FOR", value:59, real_team:"Arsenal")
Player.create(name:"Alexis Sánchez", position:"FOR", value:82, real_team:"Arsenal")
Player.create(name:"Theo Walcott", position:"FOR", value:67, real_team:"Arsenal")
Player.create(name:"Joel Campbell", position:"FOR", value:55, real_team:"Arsenal")
Player.create(name:"Olivier Giroud", position:"FOR", value:65, real_team:"Arsenal")
Player.create(name:"Danny Welbeck", position:"FOR", value:62, real_team:"Arsenal")
Player.create(name:"Petr Cech", position:"GK", value:52, real_team:"Arsenal")
Player.create(name:"Mohamed Elneny", position:"MID", value:55, real_team:"Arsenal")
Player.create(name:"Gabriel Paulista", position:"DEF", value:56, real_team:"Arsenal")
Player.create(name:"Matt Macey", position:"GK", value:55, real_team:"Arsenal")
Player.create(name:"Alex Iwobi", position:"FOR", value:53, real_team:"Arsenal")
Player.create(name:"Abdul Rahman Baba", position:"DEF", value:55, real_team:"Chelsea")
Player.create(name:"Falcao", position:"FOR", value:72, real_team:"Chelsea")
Player.create(name:"Asmir Begovic", position:"GK", value:56, real_team:"Chelsea")
Player.create(name:"Thibaut Courtois", position:"GK", value:71, real_team:"Chelsea")
Player.create(name:"Jamal Blackman", position:"GK", value:54, real_team:"Chelsea")
Player.create(name:"Gary Cahill", position:"DEF", value:60, real_team:"Chelsea")
Player.create(name:"Kurt Zouma", position:"DEF", value:55, real_team:"Chelsea")
Player.create(name:"John Terry", position:"DEF", value:52, real_team:"Chelsea")
Player.create(name:"César Azpilicueta", position:"DEF", value:66, real_team:"Chelsea")
Player.create(name:"Branislav Ivanovic", position:"DEF", value:57, real_team:"Chelsea")
Player.create(name:"Nemanja Matic", position:"MID", value:71, real_team:"Chelsea")
Player.create(name:"John Obi Mikel", position:"MID", value:57, real_team:"Chelsea")
Player.create(name:"Cesc Fàbregas", position:"MID", value:75, real_team:"Chelsea")
Player.create(name:"Oscar", position:"MID", value:71, real_team:"Chelsea")
Player.create(name:"Willian", position:"FOR", value:67, real_team:"Chelsea")
Player.create(name:"Eden Hazard", position:"FOR", value:86, real_team:"Chelsea")
Player.create(name:"Diego Costa", position:"FOR", value:75, real_team:"Chelsea")
Player.create(name:"Loïc Rémy", position:"FOR", value:57, real_team:"Chelsea")
Player.create(name:"Pedro", position:"FOR", value:67, real_team:"Chelsea")
Player.create(name:"Ruben Loftus-Cheek", position:"MID", value:53, real_team:"Chelsea")
Player.create(name:"Kenedy", position:"FOR", value:54, real_team:"Chelsea")
Player.create(name:"Bertrand Traoré", position:"FOR", value:55, real_team:"Chelsea")
Player.create(name:"Marco Amelia", position:"GK", value:53, real_team:"Chelsea")
Player.create(name:"Matt Miazga", position:"DEF", value:55, real_team:"Chelsea")
Player.create(name:"Alexandre Pato", position:"FOR", value:57, real_team:"Chelsea")
Player.create(name:"Kevin Wimmer", position:"DEF", value:55, real_team:"Spurs")
Player.create(name:"Heung-Min Son", position:"FOR", value:65, real_team:"Spurs")
Player.create(name:"Tom Carroll", position:"MID", value:57, real_team:"Spurs")
Player.create(name:"Hugo Lloris", position:"GK", value:67, real_team:"Spurs")
Player.create(name:"Michel Vorm", position:"GK", value:52, real_team:"Spurs")
Player.create(name:"Jan Vertonghen", position:"DEF", value:61, real_team:"Spurs")
Player.create(name:"Eric Dier", position:"MID", value:54, real_team:"Spurs")
Player.create(name:"Ben Davies", position:"DEF", value:55, real_team:"Spurs")
Player.create(name:"Danny Rose", position:"DEF", value:56, real_team:"Spurs")
Player.create(name:"Kyle Walker", position:"DEF", value:57, real_team:"Spurs")
Player.create(name:"Moussa Dembélé", position:"MID", value:57, real_team:"Spurs")
Player.create(name:"Nabil Bentaleb", position:"MID", value:53, real_team:"Spurs")
Player.create(name:"Ryan Mason", position:"MID", value:55, real_team:"Spurs")
Player.create(name:"Christian Eriksen", position:"MID", value:66, real_team:"Spurs")
Player.create(name:"Nacer Chadli", position:"FOR", value:57, real_team:"Spurs")
Player.create(name:"Érik Lamela", position:"FOR", value:66, real_team:"Spurs")
Player.create(name:"Harry Kane", position:"FOR", value:65, real_team:"Spurs")
Player.create(name:"Toby Alderweireld", position:"DEF", value:55, real_team:"Spurs")
Player.create(name:"Kieran Trippier", position:"DEF", value:57, real_team:"Spurs")
Player.create(name:"Clinton N'Jie", position:"FOR", value:53, real_team:"Spurs")
Player.create(name:"Dele Alli", position:"MID", value:54, real_team:"Spurs")
Player.create(name:"Josh Onomah", position:"MID", value:53, real_team:"Spurs")
Player.create(name:"Pepe Reina", position:"GK", value:52, real_team:"Napoli")
Player.create(name:"Rafael", position:"GK", value:55, real_team:"Napoli")
Player.create(name:"Alberto Grassi", position:"MID", value:55, real_team:"Napoli")
Player.create(name:"Vasco Regini", position:"DEF", value:56, real_team:"Napoli")
Player.create(name:"Allan", position:"MID", value:62, real_team:"Napoli")
Player.create(name:"Elseid Hysaj", position:"DEF", value:55, real_team:"Napoli")
Player.create(name:"Mirko Valdifiori", position:"MID", value:56, real_team:"Napoli")
Player.create(name:"Raúl Albiol", position:"DEF", value:57, real_team:"Napoli")
Player.create(name:"Kalidou Koulibaly", position:"DEF", value:62, real_team:"Napoli")
Player.create(name:"Faouzi Ghoulam", position:"DEF", value:55, real_team:"Napoli")
Player.create(name:"Ivan Strinic", position:"DEF", value:56, real_team:"Napoli")
Player.create(name:"Christian Maggio", position:"DEF", value:53, real_team:"Napoli")
Player.create(name:"David López", position:"MID", value:57, real_team:"Napoli")
Player.create(name:"Jorginho", position:"MID", value:61, real_team:"Napoli")
Player.create(name:"Marek Hamsik", position:"MID", value:71, real_team:"Napoli")
Player.create(name:"Dries Mertens", position:"FOR", value:60, real_team:"Napoli")
Player.create(name:"Lorenzo Insigne", position:"FOR", value:66, real_team:"Napoli")
Player.create(name:"José Callejón", position:"FOR", value:60, real_team:"Napoli")
Player.create(name:"Manolo Gabbiadini", position:"FOR", value:60, real_team:"Napoli")
Player.create(name:"Gonzalo Higuaín", position:"FOR", value:82, real_team:"Napoli")
Player.create(name:"Omar El Kaddouri", position:"MID", value:57, real_team:"Napoli")
Player.create(name:"Vlad Chiriches", position:"DEF", value:57, real_team:"Napoli")
Player.create(name:"Gabriel", position:"GK", value:56, real_team:"Napoli")
Player.create(name:"Sebastiano Luperto", position:"DEF", value:54, real_team:"Napoli")
Player.create(name:"Nathaniel Chalobah", position:"MID", value:55, real_team:"Napoli")
Player.create(name:"Ivan Perisic", position:"FOR", value:62, real_team:"Inter")
Player.create(name:"Adem Ljajic", position:"FOR", value:57, real_team:"Inter")
Player.create(name:"Jonathan Biabiany", position:"FOR", value:56, real_team:"Inter")
Player.create(name:"Samir Handanovic", position:"GK", value:54, real_team:"Inter")
Player.create(name:"Juan Pablo Carrizo", position:"GK", value:54, real_team:"Inter")
Player.create(name:"Tommaso Berni", position:"GK", value:52, real_team:"Inter")
Player.create(name:"Juan Jesus", position:"DEF", value:57, real_team:"Inter")
Player.create(name:"Yuto Nagatomo", position:"DEF", value:55, real_team:"Inter")
Player.create(name:"Danilo D'Ambrosio", position:"DEF", value:55, real_team:"Inter")
Player.create(name:"Gary Medel", position:"MID", value:56, real_team:"Inter")
Player.create(name:"Rodrigo Palacio", position:"FOR", value:52, real_team:"Inter")
Player.create(name:"Mauro Icardi", position:"FOR", value:72, real_team:"Inter")
Player.create(name:"Davide Santon", position:"DEF", value:56, real_team:"Inter")
Player.create(name:"Stevan Jovetic", position:"FOR", value:61, real_team:"Inter")
Player.create(name:"Alex Telles", position:"DEF", value:56, real_team:"Inter")
Player.create(name:"Felipe Melo", position:"MID", value:52, real_team:"Inter")
Player.create(name:"Geoffrey Kondogbia", position:"MID", value:67, real_team:"Inter")
Player.create(name:"Jeison Murillo", position:"DEF", value:62, real_team:"Inter")
Player.create(name:"Miranda", position:"DEF", value:58, real_team:"Inter")
Player.create(name:"Éder", position:"FOR", value:57, real_team:"Inter")
Player.create(name:"Marcelo Brozovic", position:"MID", value:57, real_team:"Inter")
Player.create(name:"Assane Gnoukouri", position:"MID", value:54, real_team:"Inter")
Player.create(name:"Rey Manaj", position:"FOR", value:55, real_team:"Inter")
Player.create(name:"Aarón Ñíguez", position:"FOR", value:55, real_team:"Braga")
Player.create(name:"Filipe Augusto", position:"MID", value:55, real_team:"Braga")
Player.create(name:"Arghus", position:"DEF", value:55, real_team:"Braga")
Player.create(name:"Ricardo Ferreira", position:"DEF", value:57, real_team:"Braga")
Player.create(name:"Ahmed Hassan", position:"FOR", value:56, real_team:"Braga")
Player.create(name:"Matheus", position:"GK", value:55, real_team:"Braga")
Player.create(name:"André Pinto", position:"DEF", value:56, real_team:"Braga")
Player.create(name:"Willy Boly", position:"DEF", value:55, real_team:"Braga")
Player.create(name:"Djavan", position:"DEF", value:56, real_team:"Braga")
Player.create(name:"Baiano", position:"DEF", value:55, real_team:"Braga")
Player.create(name:"Marcelo Goiano", position:"DEF", value:55, real_team:"Braga")
Player.create(name:"Mauro", position:"MID", value:56, real_team:"Braga")
Player.create(name:"Luíz Carlos", position:"MID", value:53, real_team:"Braga")
Player.create(name:"Nikola Vukcevic", position:"MID", value:57, real_team:"Braga")
Player.create(name:"Pedro Santos", position:"FOR", value:57, real_team:"Braga")
Player.create(name:"Rafa Silva", position:"FOR", value:53, real_team:"Braga")
Player.create(name:"Alan", position:"FOR", value:53, real_team:"Braga")
Player.create(name:"Rui Fonte", position:"FOR", value:55, real_team:"Braga")
Player.create(name:"Alef", position:"MID", value:55, real_team:"Braga")
Player.create(name:"William Pottker", position:"FOR", value:54, real_team:"Braga")
Player.create(name:"Wilson Eduardo", position:"FOR", value:55, real_team:"Braga")
Player.create(name:"Nikola Stojiljkovic", position:"FOR", value:56, real_team:"Braga")
Player.create(name:"Crislan", position:"FOR", value:56, real_team:"Braga")
Player.create(name:"Marafona", position:"GK", value:57, real_team:"Braga")
Player.create(name:"Stian Ringstad", position:"DEF", value:57, real_team:"Braga")
Player.create(name:"Josué", position:"MID", value:55, real_team:"Braga")
Player.create(name:"Amin Younes", position:"FOR", value:53, real_team:"Ajax")
Player.create(name:"Jasper Cillessen", position:"GK", value:56, real_team:"Ajax")
Player.create(name:"Diederik Boer", position:"GK", value:52, real_team:"Ajax")
Player.create(name:"Joël Veltman", position:"DEF", value:55, real_team:"Ajax")
Player.create(name:"Mike van der Hoorn", position:"DEF", value:55, real_team:"Ajax")
Player.create(name:"Kenny Tete", position:"DEF", value:55, real_team:"Ajax")
Player.create(name:"Nick Viergever", position:"DEF", value:57, real_team:"Ajax")
Player.create(name:"Jairo Riedewald", position:"DEF", value:54, real_team:"Ajax")
Player.create(name:"Ricardo van Rhijn", position:"DEF", value:57, real_team:"Ajax")
Player.create(name:"Riechedly Bazoer", position:"MID", value:55, real_team:"Ajax")
Player.create(name:"Davy Klaassen", position:"MID", value:56, real_team:"Ajax")
Player.create(name:"Thulani Serero", position:"MID", value:55, real_team:"Ajax")
Player.create(name:"Viktor Fischer", position:"FOR", value:54, real_team:"Ajax")
Player.create(name:"Lasse Schöne", position:"FOR", value:57, real_team:"Ajax")
Player.create(name:"Anwar El Ghazi", position:"FOR", value:54, real_team:"Ajax")
Player.create(name:"Richairo Zivkovic", position:"FOR", value:54, real_team:"Ajax")
Player.create(name:"Arkadiusz Milik", position:"FOR", value:54, real_team:"Ajax")
Player.create(name:"Andre Onana", position:"GK", value:54, real_team:"Ajax")
Player.create(name:"Daley Sinkgraven", position:"MID", value:53, real_team:"Ajax")
Player.create(name:"Mitchell Dijks", position:"DEF", value:55, real_team:"Ajax")
Player.create(name:"Nemanja Gudelj", position:"MID", value:55, real_team:"Ajax")
Player.create(name:"Donny van de Beek", position:"MID", value:53, real_team:"Ajax")
Player.create(name:"Vaclav Cerny", position:"FOR", value:54, real_team:"Ajax")

